repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    language_version: python3.9
    args: ["--line-length=79"]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
      - mdformat-gfm
      - mdformat-tables
      - mdformat-black
      - mdformat-beautysh
      - mdformat-config
